backend:
  name: git-gateway # Menggunakan Netlify Identity untuk otentikasi ke Git
  branch: main # Atau 'master', sesuaikan dengan branch utama Anda di GitHub

media_folder: "images/uploads" # Lokasi penyimpanan gambar yang diupload via CMS (relatif dari root proyek)
public_folder: "/images/uploads" # Path publik untuk gambar tersebut (digunakan di website)

collections:
  - name: "products" # Nama koleksi (misalnya untuk produk)
    label: "Produk Toko" # Label yang akan muncul di UI Netlify CMS
    folder: "products" # Folder tempat menyimpan file data produk (relatif dari root proyek)
    create: true # Izinkan pembuatan entri baru
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Bagaimana nama file data produk dibuat (berdasarkan judul)
    fields: # Definisi field untuk setiap produk
      - { label: "Nama Produk", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime", default: "" }
      - { label: "Gambar Produk Utama", name: "image", widget: "image", required: false }
      - { label: "Deskripsi Singkat", name: "description", widget: "text", required: false }
      - { label: "Harga (Angka saja, contoh: 150000)", name: "price", widget: "number" }
      - { label: "Stok (Opsional)", name: "stock", widget: "number", default: 0, required: false }
      - { label: "Kategori (Opsional, pisahkan dengan koma jika >1)", name: "category", widget: "string", required: false }
      - { label: "Konten Lengkap Produk (Opsional)", name: "body", widget: "markdown", required: false }
      # --- Field khusus untuk Snipcart ---
      # Pastikan data_item_id unik untuk setiap produk
      - { label: "Snipcart: Item ID Unik", name: "data_item_id", widget: "string", hint: "ID Unik Produk, cth: PROD001. JANGAN DIUBAH SETELAH PRODUK DIBUAT." }
      - { label: "Snipcart: Item Name", name: "data_item_name", widget: "string", hint: "Nama produk untuk Snipcart (biasanya sama dengan Nama Produk di atas)"}
      - { label: "Snipcart: Item Price", name: "data_item_price", widget: "number", hint: "Harga untuk Snipcart (biasanya sama dengan Harga di atas)"}
      # URL produk di website Anda. Jika belum ada halaman detail produk, bisa diisi dengan /
      - { label: "Snipcart: Item URL", name: "data_item_url", widget: "string", default: "/", hint: "URL relatif produk di website, cth: /products/nama-produknya/"}
      - { label: "Snipcart: Item Image (Opsional)", name: "data_item_image", widget: "image", required: false, hint: "Gambar untuk keranjang Snipcart (bisa sama dengan Gambar Produk Utama)"}
